# -*- coding: utf-8 -*-
"""3 Sept  Exploratory Data Analysis TITANIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8XgpdgzRZ3yL4nKs0G46cTKtPL1TybI
"""

# Import library yang diperlukan
import pandas as pd         # Untuk manipulasi data
import numpy as np          # Untuk operasi numerik
import matplotlib.pyplot as plt  # Untuk visualisasi
import seaborn as sns       # Untuk visualisasi yang lebih interaktif dan menarik

# 1. Memuat Dataset
# Dataset Titanic tersedia secara built-in di library Seaborn
titanic = sns.load_dataset('titanic')

# Menampilkan 5 baris pertama dataset untuk memahami struktur data
print("5 Baris Pertama Dataset Titanic:")
print(titanic.head())
print(titanic.tail())


# Buat kolom baru 'sex_numeric'
# Ubah 'male' menjadi 1 dan 'female' menjadi 0
titanic['sex_numeric'] = titanic['sex'].map({'male': 1, 'female': 0})

# Tampilkan beberapa baris pertama untuk verifikasi
print(titanic[['sex', 'sex_numeric']].head())

# Menampilkan 5 baris pertama dataset untuk memahami struktur data
print("5 Baris Pertama Dataset Titanic:")
print(titanic.head())

# Mendapatkan daftar dataset yang tersedia di Seaborn
datasets = sns.get_dataset_names()

# Menampilkan daftar dataset
for dataset in datasets:
    print(dataset)

# 2. Informasi Dasar dan Statistik Deskriptif
print("\nInformasi Dataset:")
print(titanic.info())

print("\nStatistik Deskriptif untuk Kolom Numerik:")
print(titanic.describe())

# 3. Analisis Missing Values
# Menghitung jumlah missing values per kolom
missing_values = titanic.isnull().sum()
print("\nJumlah Missing Values per Kolom:")
print(missing_values)

# Visualisasi missing values menggunakan heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(titanic.isnull(), cbar=False, cmap='viridis')
plt.title("Heatmap Missing Values pada Dataset Titanic")
plt.show()

# 4. Analisis Variabel Kategorik
# Distribusi jumlah penumpang berdasarkan jenis kelamin
plt.figure(figsize=(8, 6))
sns.countplot(x='sex', data=titanic, palette='pastel')
plt.title("Distribusi Penumpang Berdasarkan Jenis Kelamin")
plt.xlabel("Jenis Kelamin")
plt.ylabel("Jumlah Penumpang")
plt.show()

# Distribusi status kelangsungan hidup (Survived)
plt.figure(figsize=(8, 6))
sns.countplot(x='survived', data=titanic, palette='Set2')
plt.title("Distribusi Status Kelangsungan Hidup Penumpang")
plt.xlabel("Status (0 = Tidak Selamat, 1 = Selamat)")
plt.ylabel("Jumlah Penumpang")
plt.show()


# Distribusi status kelangsungan hidup (Survived)
plt.figure(figsize=(8, 6))
sns.countplot(x='class', data=titanic, palette='Set2')
plt.title("Distribusi Kelas Penumpang")
plt.xlabel("kelas penumpang")
plt.ylabel("Jumlah Penumpang")
plt.show()

# 5. Analisis Variabel Numerik
# Histogram Distribusi Usia (Age)
plt.figure(figsize=(8, 6))
sns.histplot(titanic['age'].dropna(), bins=30, kde=True, color='skyblue')
plt.title("Distribusi Umur Penumpang")
plt.xlabel("Umur")
plt.ylabel("Frekuensi")
plt.show()

# Boxplot Umur berdasarkan Kelas Penumpang (pclass)
plt.figure(figsize=(8, 6))
sns.boxplot(x='pclass', y='age', data=titanic, palette='Set3')
plt.title("Distribusi Umur Berdasarkan Kelas Penumpang")
plt.xlabel("Kelas Penumpang")
plt.ylabel("Umur")
plt.show()

# 6. Analisis Korelasi antar Variabel Numerik
# Hanya memilih kolom numerik agar tidak terjadi error konversi
numeric_data = titanic.select_dtypes(include=[np.number])
correlation_matrix = numeric_data.corr()
print("\nMatriks Korelasi:")
print(correlation_matrix)

# Visualisasi matriks korelasi menggunakan heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Heatmap Matriks Korelasi pada Dataset Titanic")
plt.show()

# 7. Visualisasi Hubungan Antar Variabel
# Scatter Plot: Hubungan antara Umur (age) dan Tarif (fare)
plt.figure(figsize=(8, 6))
sns.scatterplot(x='age', y='fare', data=titanic, hue='survived', palette='Set1', alpha=0.7)
plt.title("Scatter Plot: Umur vs. Tarif dengan Status Kelangsungan Hidup")
plt.xlabel("Umur")
plt.ylabel("Tarif")
plt.legend(title="Survived", loc="upper right")
plt.show()

# 8. Analisis Lanjutan: Pairplot
# Pairplot untuk melihat hubungan antar variabel numerik dan kategorik secara menyeluruh
sns.pairplot(titanic, hue='survived', palette='Set2', vars=['age', 'fare', 'pclass'])
plt.suptitle("Pairplot Variabel pada Dataset Titanic", y=1.02)
plt.show()

# 9. Kesimpulan Sementara dari EDA:
# - Dataset Titanic memiliki beberapa missing values, terutama pada kolom 'age', 'deck', dan 'embark_town'.
# - Distribusi penumpang tampak berbeda berdasarkan jenis kelamin dan status kelangsungan hidup.
# - Variabel 'fare' dan 'age' memiliki sebaran yang cukup bervariasi, dengan outlier yang terlihat di boxplot.
# - Matriks korelasi menunjukkan adanya korelasi antara variabel numerik tertentu, misalnya antara 'fare' dan 'pclass'.
# - Visualisasi hubungan (scatter plot dan pairplot) memberikan wawasan tentang interaksi antar variabel dan perbedaan antara penumpang yang selamat dan tidak.

# Visualisasi hubungan antara sex_numeric dan survived
plt.figure(figsize=(8, 6))
sns.barplot(x='sex_numeric', y='survived', data=titanic, palette='viridis')
plt.title("Tingkat Kelangsungan Hidup Berdasarkan Jenis Kelamin Numerik")
plt.xlabel("Jenis Kelamin (0: Perempuan, 1: Laki-laki)")
plt.ylabel("Tingkat Kelangsungan Hidup")
plt.xticks([0, 1], ['Perempuan', 'Laki-laki']) # Mengganti label sumbu x
plt.show()